spring:
  security:
    oauth2:
      client:
        registration:
          # 구글 로그인 추가
          google:
            client-id: ${{secrets.GOOGLE_ID}}
            client-secret: ${{ secrets.GOOGLE_CODE }}
            scope:
              - email
              - profile
          #카카오 로그인 추가
          kakao:
            client-id:
            client-secret:
            redirect-uri:
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
          #네이버 로그인 추가
          naver:
            client-id:
            client-secret:
            redirect-uri:
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
        provider: # kakao, naver만 추가로 작성
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
